# Generated by Django 5.1.7 on 2025-03-22 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('SL', 'Side Lower'), ('LB', 'Lower Berth'), ('MB', 'Middle Berth'), ('UB', 'Upper Berth')], max_length=2)),
                ('BerthNumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(63)])),
                ('Booked', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Active', models.BooleanField(default=True)),
                ('Details', models.JSONField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('Guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.Passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('RAC', 'Reservation Against Cancellation'), ('CNF', 'Confirmed'), ('WL', 'Waiting List')], max_length=3)),
                ('Active', models.BooleanField(default=True)),
                ('BookingTime', models.DateTimeField(auto_now_add=True)),
                ('Details', models.JSONField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('BerthID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.Berth')),
                ('PassengerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.Passenger')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='Ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='ticketing.Ticket'),
        ),
    ]
