# Generated by Django 5.1.7 on 2025-03-22 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='Ticket',
        ),
        migrations.AddField(
            model_name='passenger',
            name='Gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='BerthNumber',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(63)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='BerthType',
            field=models.CharField(blank=True, choices=[('SL', 'Side Lower'), ('LB', 'Lower Berth'), ('MB', 'Middle Berth'), ('UB', 'Upper Berth')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='BerthID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.berth'),
        ),
    ]
