# Generated by Django 5.1.7 on 2025-03-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_remove_passenger_ticket_passenger_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='Details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
